---
- name: Add apt repository
  apt_repository:
    repo: ppa:webupd8team/java
    filename: java
    update_cache: yes

- name: Accept Java license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  register: result
  changed_when: result.rc != 0

- name: Install Java
  apt:
    name: "{{ item }}"
  with_items:
    - oracle-java{{ oracle_java_version }}-installer
    - oracle-java{{ oracle_java_version }}-set-default
